spring:
  application:
    name: dummy-ws-1

management.endpoints.web.base-path: /actuator/info
management.endpoints.web.exposure.include: "*"

management.endpoint.shutdown.enabled: true
endpoints.shutdown.enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${eurekaServerUrl}

proxy.user: username
proxy.password: password
proxy.hostname: host
proxy.port: 3128


